tomee7.1.4Plume web project. Using the rest web service, when i try to add a new Book entity, with a POST request , i get a exception :
Root Cause

java.lang.ClassCastException: java.util.HashMap cannot be cast to bookstore.entity.Book 

Both from curl or jQuery client.